import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Script from 'next/script'
import styles from '../styles/Home.module.css'




export default function Home() {
  return (
  
    <div className={styles.container}>
      <style jsx>
         {`
        
         h2{
          font-size:38px;
         }
         h3{
          font-size:28px;
         }
         `}
      </style>
      <Head>
        <title>Hunting coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      

      <main className={styles.main}>
        <h1 className={styles.title}>
         Hunting Coders
        </h1>
        
          <div className={styles.image}>
            <Image className={styles.homeimg} src="/hunt.jpg" width={500} height={300}></Image>
          </div>
        <p className={styles.description}>
         where hunitng coders helped by hunting coders
        </p>
           

           <div >
            <Link href="/blogs"><button className={styles.btn} type='submit'>Explore Latest Blogs</button></Link>
           </div>
           <div>
           <h2>Popular Blogs</h2>
            <div>
              <h3>How to learn next.js in 2022 online </h3>
              <p>learn by doing</p>
            </div>
            <div>
              <h3>How to learn next.js in 2022 online </h3>
              <p>learn by doing</p>
            </div>
            <div>
              <h3>How to learn next.js in 2022 online </h3>
              <p>learn by doing</p>
            </div>
           </div>
       
      </main>

      
    </div>
  )
}
